services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app/backend
      - /app/backend/.venv
    networks:
      - braincraft-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    env_file:
      - ../frontend/.env.local
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - braincraft-network

networks:
  braincraft-network:
    driver: bridge
